"""Read-model for the sqlite3 repositories of the fbsrankings package"""

from fbsrankings.infrastructure.sqlite.read.affiliation_count_by_season import AffiliationCountBySeasonQueryHandler
from fbsrankings.infrastructure.sqlite.read.canceled_games import CanceledGamesQueryHandler
from fbsrankings.infrastructure.sqlite.read.game_by_id import GameByIDQueryHandler
from fbsrankings.infrastructure.sqlite.read.game_count_by_season import GameCountBySeasonQueryHandler
from fbsrankings.infrastructure.sqlite.read.season_by_id import SeasonByIDQueryHandler
from fbsrankings.infrastructure.sqlite.read.seasons import SeasonsQueryHandler
from fbsrankings.infrastructure.sqlite.read.team_by_id import TeamByIDQueryHandler
from fbsrankings.infrastructure.sqlite.read.team_count_by_season import TeamCountBySeasonQueryHandler
from fbsrankings.infrastructure.sqlite.read.query_handler import QueryHandler
