# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
        exclude: '.bumpversion.cfg'
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-use-type-annotations
-   repo: https://github.com/mgedmin/check-python-versions
    rev: "0.19.1"
    hooks:
    -   id: check-python-versions
-   repo: https://github.com/mgedmin/check-manifest
    rev: "0.48"
    hooks:
    -   id: check-manifest
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        args: [--py36-plus, --application-directories=src]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.1
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
    -   id: black
        language_version: python3.6
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-annotations
        -   flake8-broken-line
        -   flake8-bugbear
        -   flake8-builtins
        -   flake8-commas
        -   flake8-comprehensions
        -   flake8-eradicate
        -   flake8-mutable
        -   flake8-pytest-style
        -   flake8-typing-imports
        -   flake8-use-fstring
        -   pep8-naming
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
    -   id: mypy
        additional_dependencies:
        -   pydantic
        -   pytest
        -   types-dataclasses
        -   types-setuptools
        args: [--strict]
