# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.9
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: name-tests-test
        exclude: 'tests/cli/copy_files.py'
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
        exclude: '.bumpversion.cfg'
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-use-type-annotations
-   repo: https://github.com/mgedmin/check-python-versions
    rev: "0.22.1"
    hooks:
    -   id: check-python-versions
-   repo: https://github.com/mgedmin/check-manifest
    rev: "0.50"
    hooks:
    -   id: check-manifest
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.7.0
    hooks:
    -   id: setup-cfg-fmt
        args: [--max-py-version=3.12, --include-version-classifiers]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]
        exclude: _pb2\.
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
        exclude: _pb2\.
-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        language_version: python3.9
        exclude: _pb2\.
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.2
    hooks:
    -   id: flake8
        language_version: python3.9
        additional_dependencies:
        -   flake8-2020
        -   flake8-annotations
        -   flake8-broken-line
        -   flake8-bugbear
        -   flake8-builtins
        -   flake8-commas
        -   flake8-comprehensions
        -   flake8-eradicate
        -   flake8-gettext
        -   flake8-implicit-str-concat
        -   flake8-logging-format
        -   flake8-mutable
        -   flake8-no-pep420
        -   flake8-pie
        -   flake8-print
        -   flake8-pytest-style
        -   flake8-quotes
        -   flake8-raise
        -   flake8-self
        -   flake8-simplify
        -   flake8-super
        -   flake8-tidy-imports
        -   flake8-typing-imports
        -   flake8-use-fstring
        -   flake8-use-pathlib
        -   pep8-naming
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        additional_dependencies:
        -   pydantic
        -   pytest
        -   tinydb
        -   types-beautifulsoup4
        -   types-dataclasses
        -   types-prettytable
        -   types-protobuf
        -   types-setuptools
        -   types-tqdm
        args: [--strict]
        exclude: (whitelist\.py|_pb2\.py)
