# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-added-large-files
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: forbid-new-submodules
    -   id: mixed-line-ending
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
        exclude: '.bumpversion.cfg'
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.5.1
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-use-type-annotations
-   repo: https://github.com/mgedmin/check-python-versions
    rev: "0.15.0"
    hooks:
    -   id: check-python-versions
-   repo: https://github.com/mgedmin/check-manifest
    rev: "0.42"
    hooks:
    -   id: check-manifest
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.11.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.5
    hooks:
    -   id: reorder-python-imports
        args: [--py36-plus, --application-directories=src]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.3
    hooks:
    -   id: python-safety-dependencies-check
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        language_version: python3.6
-   repo: https://github.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        additional_dependencies: ["flake8-black", "flake8-bugbear", "flake8-commas", "flake8-import-order", "pep8-naming"]
-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.5.0
    hooks:
    -   id: pylint
        additional_dependencies: [bs4, jsonschema, numpy, prettytable, pypika, tqdm, typeguard, typing_extensions]
-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
    - id: bandit
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
        additional_dependencies: [typeguard, "git+https://github.com/numpy/numpy-stubs"]
        args: [--strict]
