# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fbsrankings/messages/command/import_season_by_year.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'fbsrankings/messages/command/import_season_by_year.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fbsrankings.messages.options import options_pb2 as fbsrankings_dot_messages_dot_options_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8fbsrankings/messages/command/import_season_by_year.proto\x12\x1c\x66\x62srankings.messages.command\x1a*fbsrankings/messages/options/options.proto\"l\n\x19ImportSeasonByYearCommand\x12\x12\n\ncommand_id\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\x05:-\x82\xb5\x18)fbsrankings.command.import_season_by_yearb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fbsrankings.messages.command.import_season_by_year_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMPORTSEASONBYYEARCOMMAND']._loaded_options = None
  _globals['_IMPORTSEASONBYYEARCOMMAND']._serialized_options = b'\202\265\030)fbsrankings.command.import_season_by_year'
  _globals['_IMPORTSEASONBYYEARCOMMAND']._serialized_start=134
  _globals['_IMPORTSEASONBYYEARCOMMAND']._serialized_end=242
# @@protoc_insertion_point(module_scope)
