# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fbsrankings/messages/event/ranking.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'fbsrankings/messages/event/ranking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(fbsrankings/messages/event/ranking.proto\x12\x1a\x66\x62srankings.messages.event\"F\n\x0cRankingValue\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05order\x18\x02 \x01(\x05\x12\x0c\n\x04rank\x18\x03 \x01(\x05\x12\r\n\x05value\x18\x04 \x01(\x02\"\xb9\x01\n\x1aTeamRankingCalculatedEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nranking_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\tseason_id\x18\x04 \x01(\t\x12\x11\n\x04week\x18\x05 \x01(\x05H\x00\x88\x01\x01\x12\x38\n\x06values\x18\x06 \x03(\x0b\x32(.fbsrankings.messages.event.RankingValueB\x07\n\x05_week\"\xb9\x01\n\x1aGameRankingCalculatedEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nranking_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\tseason_id\x18\x04 \x01(\t\x12\x11\n\x04week\x18\x05 \x01(\x05H\x00\x88\x01\x01\x12\x38\n\x06values\x18\x06 \x03(\x0b\x32(.fbsrankings.messages.event.RankingValueB\x07\n\x05_weekb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fbsrankings.messages.event.ranking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RANKINGVALUE']._serialized_start=72
  _globals['_RANKINGVALUE']._serialized_end=142
  _globals['_TEAMRANKINGCALCULATEDEVENT']._serialized_start=145
  _globals['_TEAMRANKINGCALCULATEDEVENT']._serialized_end=330
  _globals['_GAMERANKINGCALCULATEDEVENT']._serialized_start=333
  _globals['_GAMERANKINGCALCULATEDEVENT']._serialized_end=518
# @@protoc_insertion_point(module_scope)
