# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fbsrankings/messages/enums/enums.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'fbsrankings/messages/enums/enums.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&fbsrankings/messages/enums/enums.proto\x12\x1a\x66\x62srankings.messages.enums*T\n\x0bSubdivision\x12\x1b\n\x17SUBDIVISION_UNSPECIFIED\x10\x00\x12\x13\n\x0fSUBDIVISION_FBS\x10\x01\x12\x13\n\x0fSUBDIVISION_FCS\x10\x02*q\n\rSeasonSection\x12\x1e\n\x1aSEASON_SECTION_UNSPECIFIED\x10\x00\x12!\n\x1dSEASON_SECTION_REGULAR_SEASON\x10\x01\x12\x1d\n\x19SEASON_SECTION_POSTSEASON\x10\x02*y\n\nGameStatus\x12\x1b\n\x17GAME_STATUS_UNSPECIFIED\x10\x00\x12\x19\n\x15GAME_STATUS_SCHEDULED\x10\x01\x12\x19\n\x15GAME_STATUS_COMPLETED\x10\x02\x12\x18\n\x14GAME_STATUS_CANCELED\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fbsrankings.messages.enums.enums_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBDIVISION']._serialized_start=70
  _globals['_SUBDIVISION']._serialized_end=154
  _globals['_SEASONSECTION']._serialized_start=156
  _globals['_SEASONSECTION']._serialized_end=269
  _globals['_GAMESTATUS']._serialized_start=271
  _globals['_GAMESTATUS']._serialized_end=392
# @@protoc_insertion_point(module_scope)
