# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fbsrankings/messages/query/affiliation_count_by_season.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'fbsrankings/messages/query/affiliation_count_by_season.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<fbsrankings/messages/query/affiliation_count_by_season.proto\x12\x1a\x66\x62srankings.messages.query\"k\n\x1e\x41\x66\x66iliationCountBySeasonResult\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12\x11\n\tseason_id\x18\x02 \x01(\t\x12\x11\n\tfbs_count\x18\x03 \x01(\x05\x12\x11\n\tfcs_count\x18\x04 \x01(\x05\"D\n\x1d\x41\x66\x66iliationCountBySeasonQuery\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12\x11\n\tseason_id\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fbsrankings.messages.query.affiliation_count_by_season_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AFFILIATIONCOUNTBYSEASONRESULT']._serialized_start=92
  _globals['_AFFILIATIONCOUNTBYSEASONRESULT']._serialized_end=199
  _globals['_AFFILIATIONCOUNTBYSEASONQUERY']._serialized_start=201
  _globals['_AFFILIATIONCOUNTBYSEASONQUERY']._serialized_end=269
# @@protoc_insertion_point(module_scope)
