# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fbsrankings/messages/query/canceled_games.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'fbsrankings/messages/query/canceled_games.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from fbsrankings.messages.enums import enums_pb2 as fbsrankings_dot_messages_dot_enums_dot_enums__pb2
from fbsrankings.messages.options import options_pb2 as fbsrankings_dot_messages_dot_options_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/fbsrankings/messages/query/canceled_games.proto\x12\x1a\x66\x62srankings.messages.query\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&fbsrankings/messages/enums/enums.proto\x1a*fbsrankings/messages/options/options.proto\"\xac\x02\n\x12\x43\x61nceledGameResult\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x11\n\tseason_id\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\x12\x0c\n\x04week\x18\x04 \x01(\x05\x12(\n\x04\x64\x61te\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x41\n\x0eseason_section\x18\x06 \x01(\x0e\x32).fbsrankings.messages.enums.SeasonSection\x12\x14\n\x0chome_team_id\x18\x07 \x01(\t\x12\x16\n\x0ehome_team_name\x18\x08 \x01(\t\x12\x14\n\x0c\x61way_team_id\x18\t \x01(\t\x12\x16\n\x0e\x61way_team_name\x18\n \x01(\t\x12\r\n\x05notes\x18\x0b \x01(\t\"f\n\x13\x43\x61nceledGamesResult\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12=\n\x05games\x18\x02 \x03(\x0b\x32..fbsrankings.messages.query.CanceledGameResult\"L\n\x12\x43\x61nceledGamesQuery\x12\x10\n\x08query_id\x18\x01 \x01(\t:$\x82\xb5\x18 fbsrankings.query.canceled_gamesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fbsrankings.messages.query.canceled_games_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CANCELEDGAMESQUERY']._loaded_options = None
  _globals['_CANCELEDGAMESQUERY']._serialized_options = b'\202\265\030 fbsrankings.query.canceled_games'
  _globals['_CANCELEDGAMERESULT']._serialized_start=197
  _globals['_CANCELEDGAMERESULT']._serialized_end=497
  _globals['_CANCELEDGAMESRESULT']._serialized_start=499
  _globals['_CANCELEDGAMESRESULT']._serialized_end=601
  _globals['_CANCELEDGAMESQUERY']._serialized_start=603
  _globals['_CANCELEDGAMESQUERY']._serialized_end=679
# @@protoc_insertion_point(module_scope)
