# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fbsrankings/messages/query/postseason_game_count_by_season.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'fbsrankings/messages/query/postseason_game_count_by_season.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fbsrankings.messages.options import options_pb2 as fbsrankings_dot_messages_dot_options_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@fbsrankings/messages/query/postseason_game_count_by_season.proto\x12\x1a\x66\x62srankings.messages.query\x1a*fbsrankings/messages/options/options.proto\"W\n!PostseasonGameCountBySeasonResult\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12\x11\n\tseason_id\x18\x02 \x01(\t\x12\r\n\x05\x63ount\x18\x03 \x01(\x05\"~\n PostseasonGameCountBySeasonQuery\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12\x11\n\tseason_id\x18\x02 \x01(\t:5\x82\xb5\x18\x31\x66\x62srankings.query.postseason_game_count_by_seasonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fbsrankings.messages.query.postseason_game_count_by_season_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTSEASONGAMECOUNTBYSEASONQUERY']._loaded_options = None
  _globals['_POSTSEASONGAMECOUNTBYSEASONQUERY']._serialized_options = b'\202\265\0301fbsrankings.query.postseason_game_count_by_season'
  _globals['_POSTSEASONGAMECOUNTBYSEASONRESULT']._serialized_start=140
  _globals['_POSTSEASONGAMECOUNTBYSEASONRESULT']._serialized_end=227
  _globals['_POSTSEASONGAMECOUNTBYSEASONQUERY']._serialized_start=229
  _globals['_POSTSEASONGAMECOUNTBYSEASONQUERY']._serialized_end=355
# @@protoc_insertion_point(module_scope)
