# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fbsrankings/messages/query/seasons.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'fbsrankings/messages/query/seasons.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from fbsrankings.messages.options import options_pb2 as fbsrankings_dot_messages_dot_options_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(fbsrankings/messages/query/seasons.proto\x12\x1a\x66\x62srankings.messages.query\x1a*fbsrankings/messages/options/options.proto\"/\n\x0cSeasonResult\x12\x11\n\tseason_id\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\x05\"\\\n\rSeasonsResult\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12\x39\n\x07seasons\x18\x02 \x03(\x0b\x32(.fbsrankings.messages.query.SeasonResult\"?\n\x0cSeasonsQuery\x12\x10\n\x08query_id\x18\x01 \x01(\t:\x1d\x82\xb5\x18\x19\x66\x62srankings.query.seasonsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fbsrankings.messages.query.seasons_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEASONSQUERY']._loaded_options = None
  _globals['_SEASONSQUERY']._serialized_options = b'\202\265\030\031fbsrankings.query.seasons'
  _globals['_SEASONRESULT']._serialized_start=116
  _globals['_SEASONRESULT']._serialized_end=163
  _globals['_SEASONSRESULT']._serialized_start=165
  _globals['_SEASONSRESULT']._serialized_end=257
  _globals['_SEASONSQUERY']._serialized_start=259
  _globals['_SEASONSQUERY']._serialized_end=322
# @@protoc_insertion_point(module_scope)
