# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fbsrankings/messages/query/season_by_year.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'fbsrankings/messages/query/season_by_year.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/fbsrankings/messages/query/season_by_year.proto\x12\x1a\x66\x62srankings.messages.query\"4\n\x11SeasonByYearValue\x12\x11\n\tseason_id\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\x05\"c\n\x12SeasonByYearResult\x12\x42\n\x06season\x18\x01 \x01(\x0b\x32-.fbsrankings.messages.query.SeasonByYearValueH\x00\x88\x01\x01\x42\t\n\x07_season\"3\n\x11SeasonByYearQuery\x12\x10\n\x08query_id\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fbsrankings.messages.query.season_by_year_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEASONBYYEARVALUE']._serialized_start=79
  _globals['_SEASONBYYEARVALUE']._serialized_end=131
  _globals['_SEASONBYYEARRESULT']._serialized_start=133
  _globals['_SEASONBYYEARRESULT']._serialized_end=232
  _globals['_SEASONBYYEARQUERY']._serialized_start=234
  _globals['_SEASONBYYEARQUERY']._serialized_end=285
# @@protoc_insertion_point(module_scope)
