"""Query classes for the fbsrankings package"""

from fbsrankings.query.affiliation_count_by_season import AffiliationCountBySeasonQuery as AffiliationCountBySeasonQuery, AffiliationCountBySeasonResult as AffiliationCountBySeasonResult
from fbsrankings.query.canceled_games import CanceledGamesQuery as CanceledGamesQuery, CanceledGamesResult as CanceledGamesResult, CanceledGameResult as CanceledGameResult
from fbsrankings.query.game_by_id import GameByIDQuery as GameByIDQuery, GameByIDResult as GameByIDResult
from fbsrankings.query.game_count_by_season import GameCountBySeasonQuery as GameCountBySeasonQuery, GameCountBySeasonResult as GameCountBySeasonResult
from fbsrankings.query.season_by_id import SeasonByIDQuery as SeasonByIDQuery, SeasonByIDResult as SeasonByIDResult
from fbsrankings.query.seasons import SeasonsQuery as SeasonsQuery, SeasonsResult as SeasonsResult, SeasonResult as SeasonResult
from fbsrankings.query.team_by_id import TeamByIDQuery as TeamByIDQuery, TeamByIDResult as TeamByIDResult
from fbsrankings.query.team_count_by_season import TeamCountBySeasonQuery as TeamCountBySeasonQuery, TeamCountBySeasonResult as TeamCountBySeasonResult
